### PR TITLE
Qualify special functions with module name.

### LINKED ISSUE #17: clarify @define_diffrule namespaces
I think that eg
```julia
@define_diffrule SpecialFunctions.lgamma(x) = :( digamma($x) )
```
should be
```julia
@define_diffrule SpecialFunctions.lgamma(x) = :( SpecialFunctions.digamma($x) )
```
since the RHS is not necessarily evaluated in the module of the LHS. Is this correct?

Just please clarify, I would be happy to make a PR.

(cf https://github.com/JuliaStats/StatsFuns.jl/issues/49)

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #17.

Lines were broken because they became too long.

### CODE REVIEW

**Comment by tpapp** [comment]
Someone knowledgeable **please** review the line

```julia
@define_diffrule NaNMath.lgamma(x) = :(  SpecialFunctions.digamma($x)               )
```

because I am not sure about the corner cases.

**Comment by jrevels** [comment]
I assume that that's fine, but I'll ask @mlubin since his packages - e.g. JuMP - are the main users of these definitions.

**Comment by mlubin** [comment]
Actually JuMP doesn't currently use DiffRules, although we'd like to. But anyway is the issue that digamma is missing from NaNMath?

**Comment by tpapp** [comment]
The issue is that 
```julia
ForwardDiff.derivative(NaNMath.lgamma, x)
```
may be nonsensical for `x` where `NaNMath.lgamma` differs from `SpecialFunctions.lgamma`, since it uses `SpecialFunctioncs.digamma`. But it may just work if the analytic extension matches. I don't know enough about the gamma function to answer this.

In any case, unless there are objections, it would be great to merge this PR. It fixes some bugs, and I don't think it makes anything worse.

**Comment by mlubin** [comment]
I don't know enough about lgamma or digamma either, so no objection here.

**Comment by andreasnoack** [comment]
Would be great to get this one in since it is holding back downstream packages.

**Comment by jrevels** [comment]
> Actually JuMP doesn't currently use DiffRules, although we'd like to.

JuMP uses ForwardDiff, which uses DiffRules. But anyway, this seems fine. Thanks again @tpapp!

**Pull request merged**
