### PR TITLE
Increase Julia compat 1.3

### PR DESCRIPTION
**Pull request by cossio**
Increase Julia compat bound to 1.3. This is needed for https://github.com/JuliaDiff/DiffRules.jl/pull/74.

Add CI testing on 1.3 (for consistency with compat) and 1.6 (LTS).

### CODE REVIEW

**Comment by mcabbott** [comment]
Needs version bump, ideally to 1.7, after #76.

**Comment by cossio** [comment]
> Needs version bump, ideally to 1.7, after #76.

Sorry, why do we need a new version when changing a dependency compat bound? This is not implying any change in the API of DiffRules. So why should we increase version here?

**Comment by mcabbott** [comment]
Every release needs a new version. Not a breaking version, so it's more or less free.

And I think it's meant to be a minor version, not patch, in case you ever need to release a bugfix for an older version (although this is unlikely).

**Comment by cossio** [comment]
> Every release needs a new version. Not a breaking version, so it's more or less free.
> 
> And I think it's meant to be a minor version, not patch, in case you ever need to release a bugfix for an older version (although this is unlikely).

Ok. But which PRs are you planning to tag as releases? Maybe we can bundle them together and just do one release?

**Comment by cossio** [comment]
> Every release needs a new version. Not a breaking version, so it's more or less free.
> 
> And I think it's meant to be a minor version, not patch, in case you ever need to release a bugfix for an older version (although this is unlikely).

Ah ok, I think I get it. I bumped the minor version, and rebased. This should be ready to go (as soon as tests pass).

**Comment by cossio** [comment]
The CI on Julia 1.7 is failing on `mod`, by the way. But that should be addressed in a separate PR.
Can we merge this?

**Comment by cossio** [comment]
Regarding the CI test on Julia v.17, see #78

**Review by devmotion — COMMENTED** [review]
Looks good to me, but let's wait for @mcabbott's approval as well.

Can you also get rid of the branch in https://github.com/JuliaDiff/DiffRules.jl/blob/f46977e53ab7bcf2dd0ae14ae15fcffb635703fe/src/rules.jl#L86-L88? I think it's a good opportunity to remove it :slightly_smiling_face:

**Comment by cossio** [comment]
> Can you also get rid of the branch in

Done

**Review by devmotion — APPROVED** [review]
Let's wait for the tests and @mcabbott's approval.

**Comment by cossio** [comment]
Tests pass. @mcabbott do you agree to merge this?

**Pull request merged**
